### ISSUE TITLE
Restricted groups should be visible

### ISSUE THREAD

**Issue by atstojanov** [cherrytwist/client-web#438]
## Description
Restricted groups can not be deleted so this should be visible on the UI like grayed out button or completely missing:

![image.png](https://images.zenhubusercontent.com/5f3ccd6f7c7033ff3483f1b8/07817208-df32-4efd-b2b3-15b7c60eb67b)

The server should return enough information to determine which groups or elements are restricted:
- flag in the entity - useful for displaying information on the UI about that particular field.
- list of restricted - useful for UI validations on input fields.

**Comment by techsmyth** [comment]
No longer relevant as use credential based authorization
