### ISSUE TITLE
RegisrationPage + AccountRegisrtationPage contents

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/client-web#483]
## Description

As a deployer of CT I want that all new users see the relevant conditions as part of the sign up process

## Acceptance criteria

- [ ] User has the ability accept t&c for the usage of the platform

## Additional Context

Please have the contents as follows:

**Create an account on the [Ecoverse name] ecoverse**
Please fill in the details below to create a new account. 

(do not ask for the name field but generate it from the first last name)
First Name:         Last Name:
Email address:  
Password:
Confirm Password:d
[ ] I accept the <Terms of Use> and <Privacy Policy>

Button name: "Register Now"

Already have an account? <Sign in>

==========
comment: do we need the labels if there is also the prompts inside the boxes?
![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/1c530ca1-eee1-47f9-a0e0-06795dc38079)

Privacy policy: use https://cherrytwist.org/privacy/ for now but make it so that it can be easily updated. 
Terms of use: for now just create a file as part of the client.web with a simple statement that this is the terms of use - will populate later. 

Note: both privacy policy and terms of use should be ideally served as URLs from the server configuration.

**Comment by atstojanov** [comment]
Further development: The system should provide interface for 'uploading' Tems of use and Privacy documents in the system, which later to be visualized. Would be nice to support markdown. Same is valid for the 'cookies notice'.

We need information about third party licenses.
