### ISSUE TITLE
BUG: Incorrect "auth" redirect

### ISSUE THREAD

**Issue by Comoque1** [cherrytwist/client-web#506]
**Describe the bug**
When unauthenticated user, navigate to  [community](https://dev.cherrytwist.org/community) or [messages](https://dev.cherrytwist.org/messages), it is redirected to incorrect auth page.

![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/a5a05e6a-b144-4aba-a08b-1a3cd25fe197)

**Comment by valentinyanakiev** [comment]
Sign in should go to the sign in page on Cherrytwist, not on AAD.
