### ISSUE TITLE
BUG: Cannot create organisation (property textID has failed the following constraints: maxLength)

### ISSUE THREAD

**Issue by pimotte** [cherrytwist/client-web#548]
**Describe the bug**
When creating an organisation, the error `DTO validation for class OrganisationInput { } failed! An instance of OrganisationInput has failed the validation: - property textID has failed the following constraints: maxLength ` appears.

**To Reproduce**

1. Log in as admin
2. Click on '...'
3. Click to admin
4. Create new organisation
5. Fill in anything as name
6. See error

**Expected behavior**
The organisation to be created.

**Screenshots**
![image](https://user-images.githubusercontent.com/5917458/114683136-10185600-9d10-11eb-82a4-c56c803ed039.png)

**Desktop (please complete the following information):**

- OS: Arch Linux
- Browser: Firefox
- Version 87.0

**Additional context**
Curl command for the specific request that causes the error (ips refer to our live environment, I removed my auth token)

```
curl 'http://143.198.248.211:4003/graphql' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0' -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'Referer: http://161.35.247.80/' -H 'content-type: application/json' -H 'Origin: http://161.35.247.80' -H 'Connection: keep-alive' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache' --data-raw '{"operationName":"createOrganization","variables":{"organisationData":{"name":"Digicampus","profileData":{"avatar":"","description":"","referencesData":[],"tagsetsData":[{"name":"skills","tags":[]},{"name":"keywords","tags":[]}]}}},"query":"mutation createOrganization($organisationData: OrganisationInput!) {\n  createOrganisation(organisationData: $organisationData) {\n    id\n    name\n    __typename\n  }\n}\n"}'
```

**Comment by techsmyth** [comment]
shows that we need full regression test suites on the client...

fyi - have just fully reworked all mutations on the server, and one of those updates was to add mandatory textID also for the organisations - UI still needs to be updated to request + send that string.

If you need a workaround you can create the org directly using the graphql api @ localhost:4000/graphql:

mutation CreateOrganisation($organisationData: CreateOrganisationInput!) {
  createOrganisation(organisationData: $organisationData) {
    name,
    members
    {
     	name
    }
  }
}


query variables:
{
  "organisationData":
  {
    "name": "Cherrytwist",
    "textID": "ct11"
  }
}

**Comment by pimotte** [comment]
Yeah, figured it was something like that. For now we're going to fill this using the populator, which should work, right?

**Comment by techsmyth** [comment]
Being updated as we speak, should be a refreshed version later today. Chat thru later...
