### ISSUE TITLE
Feedback to users when Avatars cannot be uploaded + new component

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/client-web#549]
## Description

As a user I want feedback when the avatar I selected was rejected by the server

## Acceptance criteria

- [ ] User should receive feedback, including the error message text, when they upload an image for their avatar that is rejected by the server
- [ ] Error message displayed in the notification area bottom right
- [ ] new UI component for avatars

**Comment by Comoque1** [comment]
Tested OK on Dev
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/dd7acb43-57f8-429a-bea1-b916fb012193)
