### ISSUE TITLE
BUG: Opportunity details give 404 as anonymous user

### ISSUE THREAD

**Issue by pimotte** [cherrytwist/client-web#574]
**Describe the bug**
When viewing the details of an opportunity as an unauthenticated user, it results in a 404

**To Reproduce**

1. Log out
2. Go to a challenge with opportunities
3. Click "details" on an opportunity
4. Get a 404

**Expected behavior**
I would expect either:
- The details button to be inaccessible in a similar manner to how community is inaccessible.
- The details of the opportunity to be shown.

**Screenshots**
![image](https://user-images.githubusercontent.com/5917458/116421130-db8fb880-a83e-11eb-8a0b-fc5c1f94554e.png)

**Desktop (please complete the following information):**

- OS: Linux
- Browser: Firefox
- Version 88

**Comment by Comoque1** [comment]
Hey Pim,
The big is addressed already and the fix should be deployed later today.

**Comment by Comoque1** [comment]
Closing the issue, as it is already deployed to [dev environment](https://dev.cherrytwist.org/Eco1/challenges/energy).

![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/fd3f282b-786e-4213-af64-0d57e036f2e9)
