### ISSUE TITLE
BUG: Entities are not displayed on the client after they are created

### ISSUE THREAD

**Issue by Comoque1** [cherrytwist/client-web#618]
**Describe the bug**
Entities (actorGroup, Relations and aspectOnOpportunity) are not displayed on the client after they are created.

**To Reproduce**

1. Go to https://dev.cherrytwist.org/ecoverse/cherrytwist/challenges/smart-meters/opportunities/meters8
2. Authenticate with admin
3. Create an actorGroup - the entity is successfully created, but the request returning on the client is failing
4. See error: `Variable "$ecoverseId" of required type "UUID_NAMEID!" was not provided.`
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/40539fa2-8b44-4213-ba3f-eb4d1e39fb97)

**Expected behavior**
Created entities must be displayed on the client.

**Comment by atstojanov** [comment]
Must be checked again!

**Comment by Comoque1** [comment]
Tested OK on DEV env.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/ae6b8ca6-b65b-4caf-8af8-fc056956ccb2)
