### ISSUE TITLE
Spike: usage of markdown component (display / edit) for context

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/client-web#636]
## Description

As a user I want more control over how information related to ecoverse/challenge/opportunity is displayed

## Acceptance criteria

- [x] Allow usage of headers, text-styles, bullets, etc, but keeping the look-and-feel of the application
- [x] Allow usage of GFM [remark-gfm](https://github.com/remarkjs/remark-gfm) plugin

## Additional Context

Library that can be used to achieve the functionality: [here](https://www.npmjs.com/package/react-markdown)

Outstanding work for other items:
- [ ] Able to restrict what kind of markdown features can be used. In particular do not want to: embed images, external links + validation using [rehype-sanitize](https://github.com/rehypejs/rehype-sanitize) plugin
- [ ] Able to properly format the input (ease of use) by using editor like [codemirror](https://www.npmjs.com/package/codemirror)
- [ ] Apply the MD concept accross challenges, opportunities & projects

**Comment by atstojanov** [comment]
What result should be achieved by using MD? 
- richer details page?
- visual control in the hand of the administrators?
- how images will be handled?
