### ISSUE TITLE
BUG: nameId length limitation on client doesn't correspond to the one from the server

### ISSUE THREAD

**Issue by Comoque1** [cherrytwist/client-web#660]
**Describe the bug**
NameId length limitation on client doesn't correspond to the one from the server.

**To Reproduce**

1. Using graphql create an opportunity with nameId longer than 20 symbols
2. Navigate to client to the same opportunity
3. Change a parameter of the opportunity 
4. Save the change - error is thrown that the length of the nameID is too long.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/924b229b-984b-4edc-a1db-ca573bae0948)
**Expected behavior**
Or limit the nameId length on server, or update the limitation on the client.

On server the limit is 25 characters.

**Comment by techsmyth** [comment]
Update field to have a max length of 25 on nameID fields
