### ISSUE TITLE
BUG: Number of challenges/opportunities is not visible on Activity panel for not authorized user

### ISSUE THREAD

**Issue by Comoque1** [cherrytwist/client-web#663]
**Describe the bug**
Number of challenges/opportunities is not visible on Activity panel for not authorized user.

**To Reproduce**

1. Go to https://demo.cherrytwist.org/ecoverses/dh_lls
2. Number of activity panel must display the correct number of Challenges/Opportunities, for user with no privileges to the ecoverse, but it doesn't.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/b22e32ac-70df-46fe-b867-32407c45435e)
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/eacfe739-761f-4041-a6e2-e561a177022d)

**Expected behavior**
Number of activity panel must display the correct number of Challenges/Opportunities, for user with no privileges to the ecoverse.

**Comment by techsmyth** [comment]
It should use the activity query
